-d C:\gowin_fpga\stepper_motor_controll_v1\impl\gwsynthesis\stepper_motor_controll_v1.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\gowin_fpga\stepper_motor_controll_v1\src\stepper_motor_controll_v1.cst
-cfg C:\gowin_fpga\stepper_motor_controll_v1\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
